### ISSUE TITLE
document ogbox.

### ISSUE THREAD

**Issue by daattali** [oganm/toSource#6]
no documentation makes the internet a sad panda.

**Comment by oganm** [comment]
Sad pandas are cute as shit
![](http://lolfunnymeme.com/wp-content/uploads/sadpanda.jpg)

**Comment by daattali** [comment]
shit isn't very cute

On Tue, Mar 31, 2015 at 1:24 PM, Ogan Mancarci <notifications@github.com>
wrote:

> Sad pandas are cute as shit
>
> <https://camo.githubusercontent.com/04ef99804bb7b61cde93952e5e618ea906181f2d/687474703a2f2f6c6f6c66756e6e796d656d652e636f6d2f77702d636f6e74656e742f75706c6f6164732f73616470616e64612e6a7067>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oganm/toSource/issues/6#issuecomment-88233051>.
>



-- 
http://deanattali.com

**Comment by oganm** [comment]
!()[http://fc09.deviantart.net/fs70/f/2010/233/6/9/Cute_Poo_by_ararothea.png]
